version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "/"
      - "/src/it/bundle"
      - "/src/it/core"
      - "/src/it/ext"
      - "/src/it/multimodule"
      - "/src/it/properties"
      - "/src/it/saxon"
      - "/src/it/skip"
    schedule:
      interval: "quarterly"
    groups:
      general:
        applies-to: "version-updates"
        patterns: [ "*" ]
      security:
        applies-to: "security-updates"
        patterns: [ "*" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      actions-general:
        applies-to: "version-updates"
        patterns: [ "*" ]
      actions-security:
        applies-to: "security-updates"
        patterns: [ "*" ]