#!groovy

def sharedLib = new SharedLib()

node {
    stage('Prepare') {
        sharedLib.prepare()
        sharedLib.purge()
    }
    stage('Build') {
        sharedLib.build()
    }
    stage('Integration test') {
        sharedLib.runITs()
    }
}