#!groovy

def sharedLib = new SharedLib()

node {
    stage('Prepare') {
        sharedLib.prepare()
        sharedLib.purge()
    }
    stage('Set release version number') {
        withEnv(["PATH+MAVEN=${tool 'M3'}/bin"]) {
            sh "(cd plugin; mvn versions:set -DnewVersion=${RELEASE_VERSION})"
            sh "git add -A; git commit -m 'Release version bump'"
        }
    }
    stage('Build - release') {
        sharedLib.build()
    }
    stage('Integration test - release') {
        sharedLib.runITs()
    }
    stage('Tag release') {
        sh "git tag ${RELEASE_VERSION}"
    }
    stage('Release artefacts') {
        if (!"${DRY_RUN}") {
            withEnv(["PATH+MAVEN=${tool 'M3'}/bin"]) {
                sh "(cd plugin; mvn clean deploy -P release -Dgpg.passphrase=${GPG_PASSPHRASE})"
            }
        } else {
            println 'Dry run - skipping this stage'
        }
    }
    stage('Purge') {
        sharedLib.purge()
    }
    stage('Set snapshot version number') {
        withEnv(["PATH+MAVEN=${tool 'M3'}/bin"]) {
            sh "(cd plugin; mvn versions:set -DnewVersion=${POST_RELEASE_SNAPSHOT_VERSION})"
            sh "git add -A; git commit -m 'Post-release version bump'"
        }
    }
    stage('Build - snapshot') {
        sharedLib.build()
    }
    stage('Integration test - snapshot') {
        sharedLib.runITs()
    }
    stage('Push release to origin/master') {
        if (!"${DRY_RUN}") {
            sshagent(["${GIT_CREDENTIALS_ID}"]) {
                sh "git push --set-upstream origin master; git push --tags"
            }
        } else {
            println 'Dry run - skipping this stage'
        }
    }
}