name: Java
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        platform:
          - name: linux-java11
            os: ubuntu-latest
            java: 11
          - name: linux-java17
            os: ubuntu-latest
            java: 17
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.platform.java }}
          distribution: temurin
      - name: verify
        run: mvn --batch-mode --update-snapshots clean verify